version: '3'

services:
    ctf:
        build: ./challenge
        restart: always
        privileged: true
        networks:
            - internal
    proxy:
        restart: always
        image: nginx
        ports:
            - '5010:5010'
        volumes:
            - ./build/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - default
            - internal
        depends_on:
            - ctf

networks:
    default:
    internal:
        internal: true

